### ISSUE TITLE
Build Kinetic Global Leadership Page

### ISSUE THREAD

**Issue by ldthorne** [kineticglobal/kinetic-web#100]
page 14 of mockup

**Comment by sbernheim4** [comment]
@bryancjones The page is built from a UI pov. Just waiting on the text for the bios. If you could send that to me in an email/on slack/in a word doc that'd be the easiest way.

**Comment by bryancjones** [comment]
@sbernheim4 Great, will do. Waiting to hear back on a couple edits, but I will send them all in one document when they're available. Have you written one for yourself?

**Comment by sbernheim4** [comment]
@bryancjones Yes. I'm almost done with it. I'll send it to you to approve in the next few days. Thanks

**Comment by sbernheim4** [comment]
@bryancjones I'm marking this as blocked just until we get all the info.

**Comment by bryancjones** [comment]
@sbernheim4 That makes sense. I'll edit them all and them to you in one email when I get them,

**Comment by sbernheim4** [comment]
@bryancjones perfect

**Comment by bryancjones** [comment]
@sbernheim4 Moving this from blocked to in progress (see email)

**Comment by sbernheim4** [comment]
@bryancjones I've added all the info from the email you sent me. Where should Don be cause he wasn't in the PDF and there wasn't a bio for him. Also do you still want the Board of Directors section like in the PDF and if so who should go in there

**Comment by bryancjones** [comment]
@sbernheim4 Don should be in the Board of Directors section. Jessica, Robert, and I should be in the executive committee section. And Team Members should be you and Katie. Just include Don's name and photo for now. I am waiting on the bio from Jessica

**Comment by sbernheim4** [comment]
@bryancjones sounds good. Thanks

**Comment by sbernheim4** [comment]
@bryancjones what's Don's last name?

**Comment by bryancjones** [comment]
@sbernheim4 Don MacKinnon. Sorry about that

**Comment by sbernheim4** [comment]
@bryancjones and what should I put as position. Just Board member or something else
