### ISSUE TITLE
Switch all emails for forms to use the right admin email

### ISSUE THREAD

**Issue by sbernheim4** [kineticglobal/kinetic-web#104]

**Comment by bryancjones** [comment]
@sbernheim4 @ldthorne I'm including matching of emails and forms here. I still need to draft the emails that the person who fills out the form will receive.

Get the Kinetic Handbook — general@kineticglobal.org
Contact Us — general@kineticglobal.org, bryan.jones@kineticglobal.org, katie.swoap@kineticglobal.org
Launch a Chapter — general@kineticglobal.org, bryan.jones@kineticglobal.org, jessica.bernheim@kineticglobal.org, katie.swoap@kineticglobal.org
Nominate an Advisor — general@kineticglobal.org, bryan.jones@kineticglobal.org, jessica.bernheim@kineticglobal.org, katie.swoap@kineticglobal.org
Become a Mentor — general@kineticglobal.org, bryan.jones@kineticglobal.org, jessica.bernheim@kineticglobal.org, katie.swoap@kineticglobal.org
