### ISSUE TITLE
Make "Our Solution" and "About Us" photos viewable on safari

### ISSUE THREAD

**Issue by bryancjones** [kineticglobal/kinetic-web#117]
<img width="1166" alt="screen shot 2016-09-15 at 12 14 41 pm" src="https://cloud.githubusercontent.com/assets/6509299/18557745/32ed6e7a-7b3e-11e6-8c5e-6b5c4770c695.png">

**Comment by sbernheim4** [comment]
@bryancjones @ldthorne I figured out why they won't appear. The css for these images is inline (aka, in the html and not in CSS) and so for some reason Safari isn't able to read the inline url. I'm working on getting them to appear in the same way using css now
