### ISSUE TITLE
Make nav-bar accessible on mobile

### ISSUE THREAD

**Issue by sbernheim4** [kineticglobal/kinetic-web#96]

**Comment by bryancjones** [comment]
1) The text on advisor page, 
2) The calendar page isn’t appearing on mobile (just need a link like the drive)
3) Can we add a link in the mobile navbar to navigate to website homepage on mobile (it could either be a Kinetic logo at the top of the mobile navbar or just a menu item that says "Home")

Thanks @sbernheim4 !

**Comment by sbernheim4** [comment]
@bryancjones sounds good. Concerning the Calendar nothing really pops up cause you should see something like this: 
<img width="324" alt="screen shot 2016-10-10 at 17 58 47" src="https://cloud.githubusercontent.com/assets/7121821/19252528/4cf10b18-8f13-11e6-99a4-5d35c2c4bf48.png">

**Comment by sbernheim4** [comment]
@bryancjones Should be fixed now. I don't know if the calendar site was not working cause when I tested it on a friend's iPhone and in an iPhone emulator it worked correctly. Could you just double check and if its still not working I'll make a new issue for it.
