### ISSUE TITLE
Build resources landing page

### ISSUE THREAD

**Issue by sbernheim4** [kineticglobal/kinetic-web#99]

**Comment by ldthorne** [comment]
Bryan Jones
The images for the buttons are in the images folder

**Comment by sbernheim4** [comment]
@bryancjones the desktop version is done but how would you want this to appear in mobile?

**Comment by bryancjones** [comment]
@sbernheim4 Would it be possible to stack the blue boxes vertically?

**Comment by sbernheim4** [comment]
@bryancjones it would but the images and size of the boxes would have to be much smaller to fit nicely. I'll edit it now to be vertical on mobile and then you can let me know what you want me to do from there on

**Comment by bryancjones** [comment]
@sbernheim4 That sounds good. I'll take a look at the deployment and we can adjust as needed

**Comment by sbernheim4** [comment]
@bryancjones take a look now and see if the mobile view is good. Check both by shrinking the window on your computer and by visiting it on your phone

**Comment by bryancjones** [comment]
@sbernheim4 Is there a pull request for this?

**Comment by sbernheim4** [comment]
@bryancjones sorry. My bad. I'll make it now
